### ISSUE TITLE
Sorting Buttons on Searchbar

### ISSUE THREAD

**Issue by tonystr** [GameMakerDiscord/GameMakerDiscord.github.io#3]
While the outline effect, and toggle machanism looks really nice, It clutteres the page, and makes it seem messy. My suggestion is to have them merged into the searchbar, on the right.

**Comment by christopherwk210** [comment]
Implemented in https://github.com/GameMakerDiscord/GameMakerDiscord.github.io/commit/f38256f587cf6005e1
