### ISSUE TITLE
Disc. - Show repo maintainer on repo pane?

### ISSUE THREAD

**Issue by JujuAdams** [GameMakerDiscord/GameMakerDiscord.github.io#5]

**Comment by christopherwk210** [comment]
Will there only ever be one "owner" per repo to signify who the maintainer is?

**Comment by tonystr** [comment]
good question. Is it possible to show the name of the one who's contributed the most, and if others have cotributed, add a "et al." (or whatever the english equivalent is), which can be cliked on to reveal the contributors page?
Example:
<sub>TonyStr __**et al.**__<sub> (sorry, couldn't get underlines to work here)

**Comment by christopherwk210** [comment]
Could probably do that, or just show all the users that have admin access to the repo? Should probably just show the contributors button anyway to be safe I'm thinking

**Comment by christopherwk210** [comment]
Repo maintainers are to be listed in readme's going forward as per @Sidorakh's suggestion, closing
