### ISSUE TITLE
F.Req - link to repos

### ISSUE THREAD

**Issue by tonystr** [GameMakerDiscord/GameMakerDiscord.github.io#8]
would love a feature of being able to link to a specific repo, in the website. The *best* would be if your browser URL changes by clicking on a repo, but I assume that's not too easy to do. Might be possible with JS. The next best, but still a good solution, would be a small box in each repo box (when clicked on) that displays a link to that specific repo on the page. Would be nice if clicking on the link box or an icon next to it would copy it to clipboard

**Comment by christopherwk210** [comment]
Implemented in 6a1c409054711a1131738d2159b8cdf02e0990b4
